const dimensions = {
  DRAWER_WIDTH: 300,
  NOT_FOUND_SIZE: 300,
  BREAK_POINTS: {
    STATUSES_FILTER: 1420,
    LOGIN_MODAL: 500,
    SIGNUP_MODAL: 500,
    NOT_FOUND: 600,
    COMMENTS_TEXTFIELD: 600,
    SIMPLE_TICKET: 750,
  },
};

export { dimensions };
