const roles = {
  USER_ALL: "USER_ALL",
  USER_NO_M: "USER_NO_M",
  USER_NO_CT: "USER_NO_CT",
  USER_NO_P: "USER_NO_P",
  USER_NO_PCT: "USER_NO_PCT",
  USER_NO_CTM: "USER_NO_CTM",
  USER_NO_PM: "USER_NO_PM",
  USER_NO_PCTM: "USER_NO_PCTM",
  ADMIN: "ADMIN",
  CHIEF_ADMIN: "CHIEF_ADMIN",
};

export { roles };
